before_script:
  #- pip install --no-cache-dir lxml
  - pip install --no-cache-dir ford
  - apk add --update --no-cache graphviz ttf-freefont

pages:
  script:
  - sh ./build-doc.sh -q
  - mv doc/html/ public/
  tags:
    - sphinx
  only:
    - schedules
      #- develop-staging
    #when: manual
    #except:
      #- schedules
  artifacts:
    paths:
      - public
    expire_in: 5min

